fof(initial_model, axiom, (dom(num_1) & dom(num_2) & dom(num_3) & dom(num_4) & dom(num_5) & dom(num_6) & dom(num_7) & dom(num_8) & dom(num_9))  &  (cell(num_1,num_1,num_1,num_1))  &  (cell(num_1,num_2,num_2,num_1))  &  (cell(num_1,num_3,num_3,num_1))  &  (cell(num_1,num_4,num_1,num_2))  &  (cell(num_1,num_5,num_2,num_2))  &  (cell(num_1,num_6,num_3,num_2))  &  (cell(num_1,num_7,num_1,num_3))  &  (cell(num_1,num_8,num_2,num_3))  &  (cell(num_1,num_9,num_3,num_3))  &  (cell(num_2,num_1,num_4,num_1))  &  (cell(num_2,num_2,num_5,num_1))  &  (cell(num_2,num_3,num_6,num_1))  &  (cell(num_2,num_4,num_4,num_2))  &  (cell(num_2,num_5,num_5,num_2))  &  (cell(num_2,num_6,num_6,num_2))  &  (cell(num_2,num_7,num_4,num_3))  &  (cell(num_2,num_8,num_5,num_3))  &  (cell(num_2,num_9,num_6,num_3))  &  (cell(num_3,num_1,num_7,num_1))  &  (cell(num_3,num_2,num_8,num_1))  &  (cell(num_3,num_3,num_9,num_1))  &  (cell(num_3,num_4,num_7,num_2))  &  (cell(num_3,num_5,num_8,num_2))  &  (cell(num_3,num_6,num_9,num_2))  &  (cell(num_3,num_8,num_7,num_3))  &  (cell(num_3,num_9,num_8,num_3))  &  (cell(num_3,num_9,num_9,num_3))  &  (cell(num_4,num_1,num_1,num_4))  &  (cell(num_4,num_2,num_2,num_4))  &  (cell(num_4,num_3,num_3,num_4))  &  (cell(num_4,num_4,num_1,num_5))  &  (cell(num_4,num_5,num_2,num_5))  &  (cell(num_4,num_6,num_3,num_5))  &  (cell(num_4,num_7,num_1,num_6))  &  (cell(num_4,num_8,num_2,num_6))  &  (cell(num_4,num_9,num_3,num_6))  &  (cell(num_5,num_1,num_4,num_4))  &  (cell(num_5,num_2,num_5,num_4))  &  (cell(num_5,num_3,num_6,num_4))  &  (cell(num_5,num_4,num_4,num_5))  &  (cell(num_5,num_5,num_5,num_5))  &  (cell(num_5,num_6,num_6,num_5))  &  (cell(num_5,num_7,num_4,num_6))  &  (cell(num_5,num_8,num_5,num_6))  &  (cell(num_5,num_9,num_6,num_6))  &  (cell(num_6,num_1,num_7,num_4))  &  (cell(num_6,num_2,num_8,num_4))  &  (cell(num_6,num_3,num_9,num_4))  &  (cell(num_6,num_4,num_7,num_5))  &  (cell(num_6,num_5,num_8,num_5))  &  (cell(num_6,num_6,num_9,num_5))  &  (cell(num_6,num_7,num_7,num_6))  &  (cell(num_6,num_5,num_8,num_6))  &  (cell(num_6,num_9,num_9,num_6))  &  (cell(num_7,num_1,num_1,num_7))  &  (cell(num_7,num_2,num_2,num_7))  &  (cell(num_7,num_3,num_3,num_7))  &  (cell(num_7,num_4,num_1,num_8))  &  (cell(num_7,num_5,num_2,num_8))  &  (cell(num_7,num_6,num_3,num_8))  &  (cell(num_7,num_7,num_1,num_9))  &  (cell(num_7,num_8,num_2,num_9))  &  (cell(num_7,num_9,num_3,num_9))  &  (cell(num_8,num_1,num_4,num_7))  &  (cell(num_8,num_2,num_5,num_7))  &  (cell(num_8,num_3,num_6,num_7))  &  (cell(num_8,num_4,num_4,num_8))  &  (cell(num_8,num_5,num_5,num_8))  &  (cell(num_8,num_6,num_6,num_8))  &  (cell(num_8,num_7,num_4,num_9))  &  (cell(num_8,num_8,num_5,num_9))  &  (cell(num_8,num_9,num_6,num_9))  &  (cell(num_9,num_1,num_7,num_7))  &  (cell(num_9,num_2,num_8,num_7))  &  (cell(num_9,num_3,num_9,num_7))  &  (cell(num_9,num_4,num_7,num_8))  &  (cell(num_9,num_5,num_8,num_8))  &  (cell(num_9,num_6,num_9,num_8))  &  (cell(num_9,num_7,num_7,num_9))  &  (cell(num_9,num_8,num_8,num_9))  &  (cell(num_9,num_9,num_9,num_9))). 
fof(axiom_0,axiom, ![ C, R] : ((dom(C) & dom(R)) => ((val(C,R,num_1))|(val(C,R,num_2))|(val(C,R,num_3))|(val(C,R,num_4))|(val(C,R,num_5))|(val(C,R,num_6))|(val(C,R,num_7))|(val(C,R,num_8))|(val(C,R,num_9))) )).
fof(axiom_1,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_2)) =>  goal )).
fof(axiom_2,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_3)) =>  goal )).
fof(axiom_3,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_4)) =>  goal )).
fof(axiom_4,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_5)) =>  goal )).
fof(axiom_5,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_6)) =>  goal )).
fof(axiom_6,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_7)) =>  goal )).
fof(axiom_7,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_8)) =>  goal )).
fof(axiom_8,axiom, ![ C, R] : ((val(C,R,num_1) & val(C,R,num_9)) =>  goal )).
fof(axiom_9,axiom, ![ C, R] : ((val(C,R,num_2) & val(C,R,num_3)) =>  goal )).
fof(axiom_10,axiom, ![ C, R] : ((val(C,R,num_2) & val(C,R,num_4)) =>  goal )).
fof(axiom_11,axiom, ![ C, R] : ((val(C,R,num_2) & val(C,R,num_5)) =>  goal )).
fof(axiom_12,axiom, ![ C, R] : ((val(C,R,num_2) & val(C,R,num_6)) =>  goal )).
fof(axiom_13,axiom, ![ C, R] : ((val(C,R,num_2) & val(C,R,num_7)) =>  goal )).
fof(axiom_14,axiom, ![ C, R] : ((val(C,R,num_2) & val(C,R,num_8)) =>  goal )).
fof(axiom_15,axiom, ![ C, R] : ((val(C,R,num_2) & val(C,R,num_9)) =>  goal )).
fof(axiom_16,axiom, ![ C, R] : ((val(C,R,num_3) & val(C,R,num_4)) =>  goal )).
fof(axiom_17,axiom, ![ C, R] : ((val(C,R,num_3) & val(C,R,num_5)) =>  goal )).
fof(axiom_18,axiom, ![ C, R] : ((val(C,R,num_3) & val(C,R,num_6)) =>  goal )).
fof(axiom_19,axiom, ![ C, R] : ((val(C,R,num_3) & val(C,R,num_7)) =>  goal )).
fof(axiom_20,axiom, ![ C, R] : ((val(C,R,num_3) & val(C,R,num_8)) =>  goal )).
fof(axiom_21,axiom, ![ C, R] : ((val(C,R,num_3) & val(C,R,num_9)) =>  goal )).
fof(axiom_22,axiom, ![ C, R] : ((val(C,R,num_4) & val(C,R,num_5)) =>  goal )).
fof(axiom_23,axiom, ![ C, R] : ((val(C,R,num_4) & val(C,R,num_6)) =>  goal )).
fof(axiom_24,axiom, ![ C, R] : ((val(C,R,num_4) & val(C,R,num_7)) =>  goal )).
fof(axiom_25,axiom, ![ C, R] : ((val(C,R,num_4) & val(C,R,num_8)) =>  goal )).
fof(axiom_26,axiom, ![ C, R] : ((val(C,R,num_4) & val(C,R,num_9)) =>  goal )).
fof(axiom_27,axiom, ![ C, R] : ((val(C,R,num_5) & val(C,R,num_6)) =>  goal )).
fof(axiom_28,axiom, ![ C, R] : ((val(C,R,num_5) & val(C,R,num_7)) =>  goal )).
fof(axiom_29,axiom, ![ C, R] : ((val(C,R,num_5) & val(C,R,num_8)) =>  goal )).
fof(axiom_30,axiom, ![ C, R] : ((val(C,R,num_5) & val(C,R,num_9)) =>  goal )).
fof(axiom_31,axiom, ![ C, R] : ((val(C,R,num_6) & val(C,R,num_7)) =>  goal )).
fof(axiom_32,axiom, ![ C, R] : ((val(C,R,num_6) & val(C,R,num_8)) =>  goal )).
fof(axiom_33,axiom, ![ C, R] : ((val(C,R,num_6) & val(C,R,num_9)) =>  goal )).
fof(axiom_34,axiom, ![ C, R] : ((val(C,R,num_7) & val(C,R,num_8)) =>  goal )).
fof(axiom_35,axiom, ![ C, R] : ((val(C,R,num_7) & val(C,R,num_9)) =>  goal )).
fof(axiom_36,axiom, ![ C, R] : ((val(C,R,num_8) & val(C,R,num_9)) =>  goal )).
fof(axiom_37,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_2,R,V)) =>  goal )).
fof(axiom_38,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_3,R,V)) =>  goal )).
fof(axiom_39,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_4,R,V)) =>  goal )).
fof(axiom_40,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_5,R,V)) =>  goal )).
fof(axiom_41,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_6,R,V)) =>  goal )).
fof(axiom_42,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_7,R,V)) =>  goal )).
fof(axiom_43,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_8,R,V)) =>  goal )).
fof(axiom_44,axiom, ![ R, V] : ((val(num_1,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_45,axiom, ![ R, V] : ((val(num_2,R,V) & val(num_3,R,V)) =>  goal )).
fof(axiom_46,axiom, ![ R, V] : ((val(num_2,R,V) & val(num_4,R,V)) =>  goal )).
fof(axiom_47,axiom, ![ R, V] : ((val(num_2,R,V) & val(num_5,R,V)) =>  goal )).
fof(axiom_48,axiom, ![ R, V] : ((val(num_2,R,V) & val(num_6,R,V)) =>  goal )).
fof(axiom_49,axiom, ![ R, V] : ((val(num_2,R,V) & val(num_7,R,V)) =>  goal )).
fof(axiom_50,axiom, ![ R, V] : ((val(num_2,R,V) & val(num_8,R,V)) =>  goal )).
fof(axiom_51,axiom, ![ R, V] : ((val(num_2,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_52,axiom, ![ R, V] : ((val(num_3,R,V) & val(num_4,R,V)) =>  goal )).
fof(axiom_53,axiom, ![ R, V] : ((val(num_3,R,V) & val(num_5,R,V)) =>  goal )).
fof(axiom_54,axiom, ![ R, V] : ((val(num_3,R,V) & val(num_6,R,V)) =>  goal )).
fof(axiom_55,axiom, ![ R, V] : ((val(num_3,R,V) & val(num_7,R,V)) =>  goal )).
fof(axiom_56,axiom, ![ R, V] : ((val(num_3,R,V) & val(num_8,R,V)) =>  goal )).
fof(axiom_57,axiom, ![ R, V] : ((val(num_3,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_58,axiom, ![ R, V] : ((val(num_4,R,V) & val(num_5,R,V)) =>  goal )).
fof(axiom_59,axiom, ![ R, V] : ((val(num_4,R,V) & val(num_6,R,V)) =>  goal )).
fof(axiom_60,axiom, ![ R, V] : ((val(num_4,R,V) & val(num_7,R,V)) =>  goal )).
fof(axiom_61,axiom, ![ R, V] : ((val(num_4,R,V) & val(num_8,R,V)) =>  goal )).
fof(axiom_62,axiom, ![ R, V] : ((val(num_4,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_63,axiom, ![ R, V] : ((val(num_5,R,V) & val(num_6,R,V)) =>  goal )).
fof(axiom_64,axiom, ![ R, V] : ((val(num_5,R,V) & val(num_7,R,V)) =>  goal )).
fof(axiom_65,axiom, ![ R, V] : ((val(num_5,R,V) & val(num_8,R,V)) =>  goal )).
fof(axiom_66,axiom, ![ R, V] : ((val(num_5,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_67,axiom, ![ R, V] : ((val(num_6,R,V) & val(num_7,R,V)) =>  goal )).
fof(axiom_68,axiom, ![ R, V] : ((val(num_6,R,V) & val(num_8,R,V)) =>  goal )).
fof(axiom_69,axiom, ![ R, V] : ((val(num_6,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_70,axiom, ![ R, V] : ((val(num_7,R,V) & val(num_8,R,V)) =>  goal )).
fof(axiom_71,axiom, ![ R, V] : ((val(num_7,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_72,axiom, ![ R, V] : ((val(num_8,R,V) & val(num_9,R,V)) =>  goal )).
fof(axiom_73,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_2,V)) =>  goal )).
fof(axiom_74,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_3,V)) =>  goal )).
fof(axiom_75,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_4,V)) =>  goal )).
fof(axiom_76,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_5,V)) =>  goal )).
fof(axiom_77,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_6,V)) =>  goal )).
fof(axiom_78,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_7,V)) =>  goal )).
fof(axiom_79,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_8,V)) =>  goal )).
fof(axiom_80,axiom, ![ C, V] : ((val(C,num_1,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_81,axiom, ![ C, V] : ((val(C,num_2,V) & val(C,num_3,V)) =>  goal )).
fof(axiom_82,axiom, ![ C, V] : ((val(C,num_2,V) & val(C,num_4,V)) =>  goal )).
fof(axiom_83,axiom, ![ C, V] : ((val(C,num_2,V) & val(C,num_5,V)) =>  goal )).
fof(axiom_84,axiom, ![ C, V] : ((val(C,num_2,V) & val(C,num_6,V)) =>  goal )).
fof(axiom_85,axiom, ![ C, V] : ((val(C,num_2,V) & val(C,num_7,V)) =>  goal )).
fof(axiom_86,axiom, ![ C, V] : ((val(C,num_2,V) & val(C,num_8,V)) =>  goal )).
fof(axiom_87,axiom, ![ C, V] : ((val(C,num_2,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_88,axiom, ![ C, V] : ((val(C,num_3,V) & val(C,num_4,V)) =>  goal )).
fof(axiom_89,axiom, ![ C, V] : ((val(C,num_3,V) & val(C,num_5,V)) =>  goal )).
fof(axiom_90,axiom, ![ C, V] : ((val(C,num_3,V) & val(C,num_6,V)) =>  goal )).
fof(axiom_91,axiom, ![ C, V] : ((val(C,num_3,V) & val(C,num_7,V)) =>  goal )).
fof(axiom_92,axiom, ![ C, V] : ((val(C,num_3,V) & val(C,num_8,V)) =>  goal )).
fof(axiom_93,axiom, ![ C, V] : ((val(C,num_3,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_94,axiom, ![ C, V] : ((val(C,num_4,V) & val(C,num_5,V)) =>  goal )).
fof(axiom_95,axiom, ![ C, V] : ((val(C,num_4,V) & val(C,num_6,V)) =>  goal )).
fof(axiom_96,axiom, ![ C, V] : ((val(C,num_4,V) & val(C,num_7,V)) =>  goal )).
fof(axiom_97,axiom, ![ C, V] : ((val(C,num_4,V) & val(C,num_8,V)) =>  goal )).
fof(axiom_98,axiom, ![ C, V] : ((val(C,num_4,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_99,axiom, ![ C, V] : ((val(C,num_5,V) & val(C,num_6,V)) =>  goal )).
fof(axiom_100,axiom, ![ C, V] : ((val(C,num_5,V) & val(C,num_7,V)) =>  goal )).
fof(axiom_101,axiom, ![ C, V] : ((val(C,num_5,V) & val(C,num_8,V)) =>  goal )).
fof(axiom_102,axiom, ![ C, V] : ((val(C,num_5,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_103,axiom, ![ C, V] : ((val(C,num_6,V) & val(C,num_7,V)) =>  goal )).
fof(axiom_104,axiom, ![ C, V] : ((val(C,num_6,V) & val(C,num_8,V)) =>  goal )).
fof(axiom_105,axiom, ![ C, V] : ((val(C,num_6,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_106,axiom, ![ C, V] : ((val(C,num_7,V) & val(C,num_8,V)) =>  goal )).
fof(axiom_107,axiom, ![ C, V] : ((val(C,num_7,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_108,axiom, ![ C, V] : ((val(C,num_8,V) & val(C,num_9,V)) =>  goal )).
fof(axiom_109,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_2,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_110,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_3,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_111,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_4,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_112,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_5,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_113,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_6,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_114,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_7,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_115,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_8,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_116,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_1,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_117,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_2,C1,R1) & val(C1,R1,V) & cell(Cell,num_3,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_118,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_2,C1,R1) & val(C1,R1,V) & cell(Cell,num_4,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_119,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_2,C1,R1) & val(C1,R1,V) & cell(Cell,num_5,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_120,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_2,C1,R1) & val(C1,R1,V) & cell(Cell,num_6,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_121,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_2,C1,R1) & val(C1,R1,V) & cell(Cell,num_7,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_122,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_2,C1,R1) & val(C1,R1,V) & cell(Cell,num_8,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_123,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_2,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_124,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_3,C1,R1) & val(C1,R1,V) & cell(Cell,num_4,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_125,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_3,C1,R1) & val(C1,R1,V) & cell(Cell,num_5,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_126,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_3,C1,R1) & val(C1,R1,V) & cell(Cell,num_6,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_127,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_3,C1,R1) & val(C1,R1,V) & cell(Cell,num_7,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_128,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_3,C1,R1) & val(C1,R1,V) & cell(Cell,num_8,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_129,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_3,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_130,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_4,C1,R1) & val(C1,R1,V) & cell(Cell,num_5,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_131,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_4,C1,R1) & val(C1,R1,V) & cell(Cell,num_6,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_132,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_4,C1,R1) & val(C1,R1,V) & cell(Cell,num_7,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_133,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_4,C1,R1) & val(C1,R1,V) & cell(Cell,num_8,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_134,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_4,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_135,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_5,C1,R1) & val(C1,R1,V) & cell(Cell,num_6,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_136,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_5,C1,R1) & val(C1,R1,V) & cell(Cell,num_7,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_137,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_5,C1,R1) & val(C1,R1,V) & cell(Cell,num_8,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_138,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_5,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_139,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_6,C1,R1) & val(C1,R1,V) & cell(Cell,num_7,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_140,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_6,C1,R1) & val(C1,R1,V) & cell(Cell,num_8,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_141,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_6,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_142,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_7,C1,R1) & val(C1,R1,V) & cell(Cell,num_8,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_143,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_7,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(axiom_144,axiom, ![ Cell, C1, R1, V, C2, R2] : ((cell(Cell,num_8,C1,R1) & val(C1,R1,V) & cell(Cell,num_9,C2,R2) & val(C2,R2,V)) =>  goal )).
fof(goal_to_be_proved,conjecture,( goal )).
